export const CONSTANTS = {
    BASE_URL_EEA_UTD: "http://discomap.eea.europa.eu/map/fme/latest/",
    EEA_POLLUTANT_CODES: ["PM10", "PM2.5", "CO", "SO2", "NO2", "O3", "NH3", "NO"],
    EEA_COUNTRY_CODES: [
        "BG",
        "CY",
        "CZ",
        "ES",
        "GR",
        "HR",
        "HU",
        "IE",
        "IS",
        "IT",
        "LT",
        "LU",
        "NO",
        "PT",
        "RS",
        "SE",
        "SK",
        "AD",
        "BA",
        "BE",
        "DE",
        "FI",
        "FR",
        "GB",
        "GI",
        "LV",
        "MT",
        "NL",
        "SI",
        "AT",
        "CH",
        "DK",
        "EE",
        "GE",
        "MK",
        "PL",
    ],
};
